default_language_version:
  python: python3.9
default_install_hook_types: [pre-commit,pre-push]
default_stages: [commit]

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types_or: [python]

      - id: black
        name: black formatter
        language: system
        entry: black --check
        types_or: [python]

      - id: isort
        name: isort
        language: system
        entry: isort --filter-files --check
        types_or: [python]

      - id: pylint
        name: pylint static code analyzer
        entry: pylint -rn -sn # Only display messages, don't display the score
        language: system
        types: [python]
