default_language_version:
  python: python3.9
default_install_hook_types: [pre-commit,pre-push]
default_stages: [commit]

repos:
  - repo: local
    hooks:

      - id: black
        name: black formatter
        language: system
        entry: black --check
        types_or: [python]

      - id: isort
        name: isort
        language: system
        entry: isort --filter-files --check
        types_or: [python]
