---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv tox tox-uv
      - name: Test with tox
        run: tox -e py
      - name: Run linters
        run: tox -e lint

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
